### PR TITLE
window: Fix sidebar styles

### PR DESCRIPTION
**Pull request by Exalm**
We don't use .view for sidebars, and while .sidebar provides a separator, it's not correctly positioned when folded.

### CODE REVIEW

**Comment by knuxify** [comment]
This leaves the sidebar without a background:

image

**Comment by Exalm** [comment]
Ah oops. Admittedly, I haven't tested it. It needs .background instead, let's see.

**Comment by knuxify** [comment]
Alright, LGTM :+1:

(Admittedly I knew about the GtkSeparator thing, but wasn't aware of `<child type="separator">`... :p)

**Comment by Exalm** [comment]
Well, the preferred way is <property name="separator"> but you had <child> for the other 2 so I kept that. :)

**Pull request merged**
